# **APLIKASI KAL**

### **Algoritma Page Rank**

Algoritma PageRank adalah algoritma yang digunakan untuk menentukan pentingnya suatu halaman web dalam suatu jaringan web. Algoritma ini dikembangkan oleh Larry Page dan Sergey Brin, pendiri Google, dan menjadi salah satu faktor utama dalam menentukan peringkat halaman web dalam hasil pencarian Google.

Algoritma PageRank bekerja dengan cara merepresentasikan jaringan web sebagai sebuah graf. Dalam graf ini, setiap halaman web direpresentasikan sebagai sebuah simpul (node) dan setiap tautan antara halaman web direpresentasikan sebagai sisi (edge). 

**Prinsip dasar algoritma PageRank adalah:**

* Semakin banyak halaman web yang menautkan ke suatu halaman web, semakin penting halaman web tersebut.
* Semakin penting halaman web yang menautkan ke suatu halaman web, semakin besar kontribusinya terhadap nilai PageRank halaman web tersebut.

**Langkah-langkah dalam algoritma PageRank:**

1. **Inisialisasi:** Setiap simpul dalam graf diberi nilai PageRank awal yang sama.
2. **Iterasi:**
    * Hitung nilai PageRank baru untuk setiap simpul berdasarkan nilai PageRank simpul-simpul yang menautkan ke simpul tersebut.
    * Ulangi langkah 2 hingga nilai PageRank semua simpul konvergen, yaitu tidak mengalami perubahan yang signifikan.
3. **Normalisasi:** Nilai PageRank semua simpul dinormalisasi agar memiliki nilai antara 0 dan 1.

**Rumus untuk menghitung nilai PageRank baru:**

```
PR(v) = (1 - d) / N + d * ∑(PR(u) / OutDegree(u))
```

* PR(v): Nilai PageRank baru untuk simpul v
* d: Faktor damping, nilai konstanta antara 0 dan 1 yang digunakan untuk mencegah nilai PageRank terlalu tinggi atau terlalu rendah. Nilai yang umum digunakan adalah 0.85.
* N: Jumlah total simpul dalam graf
* PR(u): Nilai PageRank simpul u
* OutDegree(u): Jumlah sisi yang keluar dari simpul u

In [1]:
import numpy as np
A = np.array([[0,0,0,0,1/3], [0,0,1/2,1,1/3], [1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
V0 = np.array([[0.2], [0.2], [0.2], [0.2], [0.2]])

V1 = A @ V0

print(V1)

[[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]


In [2]:
V2 = A @ V1
print(V2)

[[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]


In [3]:
V3 = A @ V2
print(V3)

[[0.12962963]
 [0.27407407]
 [0.15925926]
 [0.08518519]
 [0.35185185]]


In [4]:
V4 = A @ V3
print(V4)

[[0.11728395]
 [0.28209877]
 [0.16049383]
 [0.12283951]
 [0.31728395]]


In [5]:
V5= A @ V4
print(V5)

[[0.10576132]
 [0.30884774]
 [0.14485597]
 [0.11934156]
 [0.32119342]]


In [6]:
#|V(i+1)-Vi|**2 < toleransi (0,01)
a = (0.10576132 - 0.11728395)**2
b = (0.30884774 - 0.28209877)**2
c = (0.14485597 - 0.16049383)**2
d = (0.11934156 - 0.12283951)**2
e = (0.32119342 - 0.31728395)**2

f = a+b+c+d+e

print(f)

0.0011203406734407993


In [7]:
import numpy as np

def perkalianMatriks(A,v0):
  vbaru = A@v0
  return vbaru

def hitung(vbaru,vlama):
  temp = 0
  for i in range(len(vbaru)):
    temp += (vbaru[i] - vlama[i])**2
  return temp

def converge(A,v0,toleransi):
  count = 1
  vbaru = perkalianMatriks(A,v0)
  iterasi = hitung(vbaru,v0)
  print(f'v{count} = {vbaru}')
  print(f'iterasi ke-{count} = {iterasi}')
  print()
  while iterasi > toleransi :
    vbaru2 = perkalianMatriks(A,vbaru)
    iterasi = hitung(vbaru2,vbaru)
    print(f'v{count+1} = {vbaru}')
    print(f'iterasi ke-{count+1} = {iterasi}')
    print()
    vbaru = vbaru2
    count += 1
  return f'urutan = {pageRank(vbaru2)}'

def pageRank(vbaru):
  return np.argsort(vbaru,axis=0)[::-1]

A = np.array([[0,0,0,0,1/3],[0,0,1/2,1,1/3],[1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
v0 = np.array([[0.2],[0.2],[0.2],[0.2],[0.2]])
toleransi = 0.01
hasil = converge(A,v0,toleransi)
print(hasil)

v1 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]
iterasi ke-1 = [0.05555556]

v2 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]
iterasi ke-2 = [0.02395062]

v3 = [[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]
iterasi ke-3 = [0.00768176]

urutan = [[4]
 [1]
 [2]
 [0]
 [3]]
