# **DETERMINAN**

determinan matriks adalah nilai yang diperoleh dari matriks persegi. Si determinan ini adalah fungsi yang akan memetakan matriks persegi ke bilangan real. Determinan dari sebuah matriks persegi adalah sebuah skalar yang memberikan informasi tentang matriks tersebut, misalnya tentang kemungkinan untuk diinvers. matriks tersebut  harus persegi atau bujur sabfkar dan memiliki ordo yang sama misal 2x2 dan 3X3

# SIFAT SIFAT DETERMINANT

1. determinan dari matriks identitas adalah 1

yang pertama disini saya mempunyai 4 matrix                         
$
A = \begin{bmatrix}
3 & 2 \\
5 & 3 \\
\end{bmatrix}
$

$
B = \begin{bmatrix}
2 & 3 & 3 \\
4 & 2 & 1 \\
6 & 4 & 3
\end{bmatrix}
$

$
C = \begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix}
$

$
D = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$

mari kita buktikan determinant dari matrix C dan D

In [1]:
import numpy as np
a = np.array([[3,2], [5,3]])
b = np.array([[2,3,3],[4,2,1],[6,4,3]])
c = np.array([[1,0], [0,1]])
d = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(f"determinan dari matriks identitas c adalah : {np.linalg.det(c)}")
print(f"determinan dari matriks identitas d adalah : {np.linalg.det(d)}")
print()

[[3 2]
 [5 3]]

[[2 3 3]
 [4 2 1]
 [6 4 3]]

[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

determinan dari matriks identitas c adalah : 1.0
determinan dari matriks identitas d adalah : 1.0



2. $ det(c) = det (a * b) $                               
            $= det(a) * det(b)$                             
            $= A * A^I $          

dan                   

$ I = A * A^I$                            
$ detI = det(A) * det(A^I) $                                
$ detA^I = 1/detA$                                               

mari kita buktikan

In [2]:
a = np.array([[3,2], [5,3]])
B = np.linalg.inv(a)
detA = np.linalg.det(a)
detB = np.linalg.det(B)
print(f'determinan A : {detA.round()}')
print(f'determinan A invers : {detB.round()}')
C = detA * detB
print(f"det.A x det.B :",round(C))
print(a@B.round())

determinan A : -1.0
determinan A invers : -1.0
det.A x det.B : 1
[[1. 0.]
 [0. 1.]]


3. menukar baris atau kolom dari suatu matriks maka akan mengubah tanda dari determinant matriks itu sendiri. bisa dilihat matriks A2 sebagai acuan. dimana determinanya adalah 5 setelah diubah pada A3 baris 0 ke baris 1 dan juga pada A4 dirubah dari kolom 0 ke kolom 1 determinant nya menjadi -5. 

In [3]:
A2 = np.array([[1,4,2], [1,1,1], [3,2,1]])
print(A2)
print(np.linalg.det(A2).round())
print()
# merubah baris
A3 = np.array([[1,1,1], [1,4,2], [3,2,1]])
print(A3)
print(np.linalg.det(A3).round())
print()
# perubahan kolo
A4 = np.array([[4, 1, 2], [1, 1, 1], [2,3,1]])
print(A4)
print(np.linalg.det(A4).round())

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5.0

[[1 1 1]
 [1 4 2]
 [3 2 1]]
-5.0

[[4 1 2]
 [1 1 1]
 [2 3 1]]
-5.0


4. jika ada baris atau kolom dari matriks yang merupakan kelipatan dari baris atau kolom yang lain maka determinan nya adalah 0   
contoh baris kedua merupakan kelipatan dua dari baris pertama  (B1)                
contoh kolom kedua merupakan kelipatan 4 dari kolom pertama (B2)

In [4]:
B1 = np.array([[1,4,2], [2,8,4], [3,2,1]])
print(B1)
print(np.linalg.det(B1).round())
print()
B2 = np.array([[1,4,2], [2,8,3], [1,4,1]])
print(B2)
print(np.linalg.det(B2).round())

[[1 4 2]
 [2 8 4]
 [3 2 1]]
0.0

[[1 4 2]
 [2 8 3]
 [1 4 1]]
0.0


5. K = SKALAR               

$AnXn$    adalah matriks $nxn$     


$ det(KA) = K^N * det(A)$                                          

dengan contoh matriks dibawah dapat dihitung dengan:                         
$ det KA = 2^3 * 5 = 40$          


nb :
2 = skalar             
3 = jumlah ordo                    
5 = det a

pada matriks C12 dimana baris pertama merupakan hasil kali skalar dari matriks C1 (matriks c12 baris pertama hasil kali dari 1,4,2) maka determinanya **2 X detA**
mari kita buktikan:

In [5]:
C1 = np.array([[1,4,2], [1,1,1], [3,2,1]])
K = 2
KA = K * C1
print(C1)
print(np.linalg.det(KA).round())
C12 = np.array([[2,8,4], [1,1,1], [3,2,1]])
print(np.linalg.det(C12).round())

[[1 4 2]
 [1 1 1]
 [3 2 1]]
40.0
10.0


**6. MATRIKS SEGITIGA ATAS & BAWAH**    

Matriks segitiga atas : jika dibawah diagonal utama [1,1,1] adalah 0, meskipun diatas diagonal utama tidak nol. jika melakukan operasi baris elementer tidak akan merubah determinan matriks tersebut.           

Matriks segitiga bawah : jika diatas diagonal utama [1,1,1] adalah 0, meskipun dibawah diagonal utama tidak nol. jika melakukan operasi baris elementer tidak akan merubah determinan matriks tersebut.          
           
$detD1 = d1, d2, .... dn$         

hasil determinanya adalah hasil perkalian dari elemen pada diagonal itu contoh pada matriks pertama $(1 x 4 x 1)$                                           
pada contoh kedua $( 2 X 1 X 5 X 3)$

In [6]:
# MATRIKS SEGITIGA ATAS
D1 = np.array([[1,4,2], [0,4,1],[0,0,1]])
print(D1)
print(np.linalg.det(D1).round())
print()
D2 = np.array([[2,3,1,2], [0,1,2,1],[0,0,5,2], [0,0,0,3]])
print(D2)
print(np.linalg.det(D2).round())

[[1 4 2]
 [0 4 1]
 [0 0 1]]
4.0

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]]
30.0


7. melakukan operasi baris terhadap suatu matriks tidak akan merubah determinant dari suatu matriks

In [7]:
E1 = np.array([[1,4,2], [1, 1, 1],[3,2,1]])
E2 = np.array([[1,4,2], [0,-3,-1],[3,2,1]])
print(np.linalg.det(E1).round())
print(np.linalg.det(E2).round())

5.0
5.0


8. determinan $detA^1 =  detA$

In [8]:
F1 = np.array([[1,4,2], [1, 1, 1],[3,2,1]])
F1T = np.transpose(F1)
print(F1T)
print(np.linalg.det(F1).round())
print(np.linalg.det(F1T).round())

[[1 1 3]
 [4 1 2]
 [2 1 1]]
5.0
5.0


# **COFACTOR EXPANSION**

Misalkan A adalah matriks n x n. Aij didefinisikan sebagai submatriks dari A yang diperoleh dengan menghapus baris ke-i dan kolom ke-j. Ekspansi kofaktor adalah metode untuk menghitung determinan matriks dengan cara memilih elemen matriks dan mengalikannya dengan minornya. Metode ini dapat digunakan untuk matriks dengan ukuran berapa pun, namun umumnya lebih efisien untuk matriks kecil (hingga 4x4).       
cara mengitungnya adalah:                       

**1. Pilih baris atau kolom:**                         
- Pilih baris atau kolom matriks secara acak. 

**2. Hitung minor:**                   
- Untuk setiap elemen pada baris/kolom yang dipilih, hitung minornya. Minor adalah determinan submatriks yang diperoleh dengan menghapus baris/kolom yang dipilih dan elemen yang ingin dihitung.

**3. Kalikan elemen dengan minor:**                                
- Kalikan setiap elemen pada baris/kolom yang dipilih dengan minornya.

**4. Jumlahkan hasil perkalian:**                                               
- Jumlahkan semua hasil perkalian yang diperoleh pada langkah 3.

**5. Ulangi:**                         
- Ulangi langkah 1 hingga 4 untuk setiap baris/kolom matriks.

**6. Jumlahkan  hasil:**
- Ekspansi kofaktor dapat menjadi rumit untuk matriks yang lebih besar.

## **MENGHITUNG DETERMINAN MATRIX 4X4 DENGAN COFACTOR EXPANSION**         
$
A = \begin{bmatrix}
2 & 1 & 3 & 1 \\
3 & 2 & 1 & 3 \\
1 & 1 & 1 & 2 \\
2 & 3 & 1 & 1\\
\end{bmatrix}
$

disini saya akan mengambil baris ke 3                                  
$A31C31$                                  
$A32C32$                            
$A33C33$                         
$A34C34$                        
 

RUMUS COFACTOR ADALAH :                       
$ c_𝑖𝑗=(−1)^(𝑖+𝑗) 𝑑𝑒𝑡𝐴_𝑖𝑗 $ 


MAKA :                   
$C31$     =     $(-1)^3+^1 Det(M31)$                                
$C32$     =     $(-1)^3+^2 Det(M32)$                        
$C33$     =     $(-1)^3+^3 Det(M33)$                 
$C34$     =     $(-1)^3+^4 Det(M34)$                          

## 1. Mencari $DetM31$    
$                       
M31 = \begin{bmatrix}
1 & 3 & 1 \\
2 & 1 & 3 \\
3 & 1 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(-1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 

  A. mencari det(m21) dari matrix M31                               
      $
      M31C21 = \begin{bmatrix}
      3 & 1 \\
      1 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah 2                           
                                   
  B. mencari det(m22) dari matrix M31                               
      $
      M31C22 = \begin{bmatrix}
      1 & 1 \\
      3 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -2 
    
  C.  mencari det(m23) dari matrix M31                               
      $
      M31C22 = \begin{bmatrix}
      1 & 3 \\
      3 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -8

  jadi :                              
  C21   =  $2 * (-1)^2+^1 2$   =     -4                                            
  C22   =  $1 * (-1)^2+^2 -2$  =     -2                                                     
  C23   =  $3 * (-1)^2+^3 -8$  =     24                                   

  $DetM31$    = -4 + -2 + 24 = 18
  

  ## 2. Mencari $DetM32$    
$                       
M32 = \begin{bmatrix}
2 & 3 & 1 \\
3 & 1 & 3 \\
2 & 1 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(-1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 


  A. mencari det(m21) dari matrix M32                              
      $
      M32C21 = \begin{bmatrix}
      3 & 1 \\
      1 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah 2                           
                                   
  B. mencari det(m22) dari matrix M32                              
      $
      M32C22 = \begin{bmatrix}
      2 & 1 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah 0

  C. mencari det(m23) dari matrix M32                               
      $
      M32C22 = \begin{bmatrix}
      2 & 3 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -4


  jadi :                              
  C21   =  $3 * (-1)^2+^1 2$   =    -6                                           
  C22   =  $1 * (-1)^2+^2 0$  =      0                                                  
  C23   =  $3 * (-1)^2+^3 -4$  =     12                                  

  $DetM32$    = -6 + 12 = 6


## 3. Mencari $DetM33$    
$                       
M33 = \begin{bmatrix}
2 & 1 & 1 \\
3 & 2 & 3 \\
2 & 3 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(-1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 

  A. mencari det(m21) dari matrix M33                              
      $
      M33C21 = \begin{bmatrix}
      1 & 1 \\
      3 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah - 2                           
                                   
  B. mencari det(m22) dari matrix M33                              
      $
      M33C22 = \begin{bmatrix}
      2 & 1 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah 0

  C. mencari det(m23) dari matrix M33                               
      $
      M33C22 = \begin{bmatrix}
      2 & 1 \\
      2 & 3\\                                                  
      \end{bmatrix}
      $
      determinannya M23 adalah 4

  jadi :                              
  C21   =  $3 * (-1)^2+^1 -2$ =    6                                          
  C22   =  $2 * (-1)^2+^2 0$  =    0                                                  
  C23   =  $3 * (-1)^2+^3 4$  =    -12                                  

  $DetM33$    = 6 + -12 = -6

## 4. Mencari $DetM34$    
$                       
M34 = \begin{bmatrix}
2 & 1 & 3 \\
3 & 2 & 1 \\
2 & 3 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(-1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 

 A. mencari det(m21) dari matrix M34                             
      $
      M34C21 = \begin{bmatrix}
      1 & 3 \\
      3 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah - 8                        
                                   
  B. mencari det(m22) dari matrix M34                              
      $
      M34C22 = \begin{bmatrix}
      2 & 3 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -4

  C. mencari det(m23) dari matrix M34                              
      $
      M34C22 = \begin{bmatrix}
      2 & 1 \\
      2 & 3\\                                                  
      \end{bmatrix}
      $
      determinannya M23 adalah 4

  jadi :                              
  C21   =  $3 * (-1)^2+^1 -8$ =    24                                         
  C22   =  $2 * (-1)^2+^2 -4$ =    -8                                                  
  C23   =  $1 * (-1)^2+^3 4$  =    -4                                 

  $DetM34$    = 24 + -8 + -4 = 12

# hitung determinan Matriks A
$C31$     =     $1*(-1)^3+^1 18$      =   18                          
$C32$     =     $1*(-1)^3+^2 6$       =   -6               
$C33$     =     $1*(-1)^3+^3 -6$      =   -6          
$C34$     =     $2*(-1)^3+^4 12$      =   -24   
dapat disimpulkan bahwa                                                                                              
$Det matriks A$    = 18 + -6 + -6 + -24 = -18                                  
mari kita buktikan:

In [9]:
A2 = np.array([[2,1,3,1], [3,2,1,3],[1,1,1,2],[2,3,1,1]])
print(A2)
print(np.linalg.det(A2).round())

[[2 1 3 1]
 [3 2 1 3]
 [1 1 1 2]
 [2 3 1 1]]
-18.0


SUMBER :
- https://www.zenius.net/blog/determinan-matriks
- https://id.wikipedia.org/wiki/Determinan
- https://www.ruangguru.com/blog/cara-mencari-determinan-dan-invers-matriks
- https://www.kompas.com/skola/read/2023/05/26/214500269/cara-mencari-determinan-matriks-ordo-3x3