# **MATRIX**
Matriks adalah susunan angka yang rapi, tersusun dalam baris dan kolom. Bayangkan seperti tabel persegi panjang, di mana setiap kotaknya berisi angka. Angka-angka ini disebut elemen matriks.

Setiap elemen memiliki alamat unik, yaitu baris dan kolomnya. Misalkan sebuah matriks bernama A dengan m baris dan n kolom. Elemen pada baris ke-i dan kolom ke-j dinotasikan sebagai a sub i,j.
A = $$ \begin{bmatrix} a_{11} & a_{12} & \dots & a_{1n} \\ a_{21} & a_{22} & \dots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \dots & a_{mn} \end{bmatrix}  $$

Di mana \( a_{ij} \) merupakan elemen pada baris ke-\( i \) dan kolom ke-\( j \).

   
   



### **OPERASI MATRIKS**
Operasi matriks adalah serangkaian operasi atau tindakan yang dilakukan pada matriks, baik itu untuk mengubah matriks ataupun menggabungkan matriks. Berikut beberapa operasi matriks yang sering digunakan:

In [1]:
import numpy as np
import sympy as sy

a=np.array([[4,2,1],[5,3,1],[2,-3,4]])
b=np.array([[3,2,6],[7,1,4],[2,-2,6]])
c=np.array([[5,2],[-4,7],[6,5]])
print('A=\n',a)
print('B=\n',b)
print('C=\n',c)

A=
 [[ 4  2  1]
 [ 5  3  1]
 [ 2 -3  4]]
B=
 [[ 3  2  6]
 [ 7  1  4]
 [ 2 -2  6]]
C=
 [[ 5  2]
 [-4  7]
 [ 6  5]]


### **1.Penjumlahan matriks :**

Operasi ini menambahkan elemen elemen dari dua matriks yang memiliki ordo yang sama. nah, kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENJUMLAHAN MATRIKS A + B :          
matriks \( A \):
$
A = \begin{bmatrix}
4 & 2 & 1 \\
5 & 3 & 1 \\
2 & -3 & 4
\end{bmatrix}
$


Matriks \( B \):
$
B = \begin{bmatrix}
3 & 2 & 6 \\
7 & 1 & 4 \\
2 & -2 & 6
\end{bmatrix}
$

Hasil Penjumlahan Matriks \( A \) dan \( B \):       
$
A + B = \begin{bmatrix}
4+3 & 2+2 & 1+6 \\
5+7 & 3+1 & 1+4 \\
2+2 & -3-2 & 4+6
\end{bmatrix}  
$   
Jadi, hasil penjumlahan dari matriks \( A \) dan \( B \) adalah:              
$
A + B = \begin{bmatrix}
7 & 4 & 7 \\
12 & 4 & 5 \\
4 & -5 & 10
\end{bmatrix}
$
    
    
BERIKUT PROGRAM UNTUK PENJUMLAHAN MATRIKS:



In [2]:
print('A+B=\n',a+b)
print('B+A=\n',b+a)
print('Sifat di atas merupakan sifat komutatif karena A+B = B+A')

A+B=
 [[ 7  4  7]
 [12  4  5]
 [ 4 -5 10]]
B+A=
 [[ 7  4  7]
 [12  4  5]
 [ 4 -5 10]]
Sifat di atas merupakan sifat komutatif karena A+B = B+A


## **2.Pengurangan Matriks:**

Operasi ini mengurangi elemen-elemen dari dua matriks yang memiliki ordo yang sama. kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENGURANGAN MATRIKS:   
Matriks \( A \):
$$
A = \begin{bmatrix}
4 & 2 & 1 \\
5 & 3 & 1 \\
2 & -3 & 4
\end{bmatrix}
$$

Matriks \( B \):
$$
B = \begin{bmatrix}
3 & 2 & 6 \\
7 & 1 & 4 \\
2 & -2 & 6
\end{bmatrix}
$$

Hasil Pengurangan Matriks \( A \) dan \( B \):                                  
$$
A - B = \begin{bmatrix}
4-3 & 2-2 & 1-6 \\
5-7 & 3-1 & 1-4 \\
2-2 & -3-(-2) & 4-6
\end{bmatrix}
$$

                            
Jadi, hasil pengurangan dari matriks \( A \) dan \( B \) adalah:              
$$
A - B = \begin{bmatrix}
1 & 0 & -5 \\
-2 & 2 & -3 \\
0 & -1 & -2
\end{bmatrix}
$$
BERIKUT PROGRAM UNTUK PENGURANGAN MATRIKS:

In [3]:
print('A-B=\n',a-b)
print('B-A=\n',b-a)
print('Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A')

A-B=
 [[ 1  0 -5]
 [-2  2 -3]
 [ 0 -1 -2]]
B-A=
 [[-1  0  5]
 [ 2 -2  3]
 [ 0  1  2]]
Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A


## **3.Perkalian Matriks:**

Perkalian matriks melibatkan operasi matematika pada elemen-elemen individual matriks. Agar dua matriks dapat dikalikan, jumlah kolom pada matriks pertama harus sama dengan jumlah baris pada matriks kedua.

Misalkan matriks A memiliki dimensi mxn, dan matriks B memiliki dimensi nxp.

Syarat:

Jumlah kolom A (n) harus sama dengan jumlah baris B (n).
Hasilnya
- Perkalian menghasilkan matriks baru dengan dimensi mxp.    
- Jumlah baris pada matriks hasil sama dengan jumlah baris A (m).     
- Jumlah kolom pada matriks hasil sama dengan jumlah kolom B (p).                          

**Proses Perkalian:**

- Kalikan elemen baris pertama A dengan setiap elemen kolom pertama B.                    
- Jumlahkan hasil perkalian ini untuk mendapatkan elemen (1,1) pada matriks hasil.               
- Ulangi langkah 1 untuk elemen baris pertama A dengan setiap kolom B lainnya. 
Ini akan menghasilkan elemen (1,2), (1,3), ..., (1,p) pada matriks hasil.                  
- Ulangi langkah 1 dan 2 untuk baris kedua A, baris ketiga A, dan seterusny               

CONTOH PERKALIAN MATRIKS:


Dengan menggunakan matriks \(A\) dan \(B\) yang Anda berikan, mari kita hitung hasil perkalian \(A \times B\):

 A = 
 $$\begin{bmatrix} 4 & 2 & 1 \\ 5 & 3 & 1 \\ 2 & -3 & 4 \end{bmatrix} $$

 B = 
 $$\begin{bmatrix} 3 & 2 & 6 \\ 7 & 1 & 4 \\ 2 & -2 & 6 \end{bmatrix}$$

Untuk menghitung hasil perkalian matriks, kita dapat menggunakan aturan perkalian matriks, yaitu mengalikan setiap elemen baris pertama dari matriks \(A\) dengan setiap elemen kolom pertama dari matriks \(B\), dan seterusnya.   



A × B = 
$$\begin{bmatrix} 4 \times 3 + 2 \times 7 + 1 \times 2 & 4 \times 2 + 2 \times 1 + 1 \times (-2) & 4 \times 6 + 2 \times 4 + 1 \times 6 \\ 5 \times 3 + 3 \times 7 + 1 \times 2 & 5 \times 2 + 3 \times 1 + 1 \times (-2) & 5 \times 6 + 3 \times 4 + 1 \times 6 \\ 2 \times 3 + (-3) \times 7 + 4 \times 2 & 2 \times 2 + (-3) \times 1 + 4 \times (-2) & 2 \times 6 + (-3) \times 4 + 4 \times 6 \end{bmatrix}$$




Jadi, hasil perkalian matriks \(A\) dan \(B\) adalah:

 A x B = 
 $$\begin{bmatrix} 24 & 2 & 32 \\ 38 & 3 & 44 \\ -13 & -12 & 10 \end{bmatrix}$$

BERIKUT PROGRAM UNTUK PERKALIAN MATRIKS:

In [4]:
print('AB=\n',a@b)
print('AC=\n',a@c)
print('BC=\n',b@c)

AB=
 [[28  8 38]
 [38 11 48]
 [-7 -7 24]]
AC=
 [[18 27]
 [19 36]
 [46  3]]
BC=
 [[43 50]
 [55 41]
 [54 20]]


## **4.Transpose Matriks**

Transpose matriks adalah matriks baru yang diperoleh dengan cara menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya. Jika sebuah matriks berukuran M X N, maka transpose matriks tersebut memiliki ordo N X M.

CONTOH TRANSPOSE MATRIKS:
$$
\begin{align*}
C=
\begin{bmatrix}
3&4\\
-2&4\\
2&5
\end{bmatrix}
&&
CT (C Transposre)=
\begin{bmatrix}
3&-2&2\\
4&4&-5
\end{bmatrix}
\end{align*}
$$
BERIKUT PROGRAM UNTUK MENG-TRANSPOSE MATRIKS:

In [5]:
c=np.array([[3,4],[-2,4],[2,5]])
c_tran = c.transpose()
print('matrik c sebelum di transpose=\n', c)
print('matrik c setelah di transpose=\n',c_tran)
print('ordo C_transpose adalah',c_tran.shape)
z=c_tran@c
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=c@c_tran
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)
print("Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose")

matrik c sebelum di transpose=
 [[ 3  4]
 [-2  4]
 [ 2  5]]
matrik c setelah di transpose=
 [[ 3 -2  2]
 [ 4  4  5]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[17 14]
 [14 57]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[25 10 26]
 [10 20 16]
 [26 16 29]]
ordo P adalah (3, 3)
Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose


In [6]:
#MENGALIKAN MATRIX

def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)

#JIKA USER INGIN MENGINPUTKAN MATRIKSNYA SENDIRI BISA MENGGUNAKAN CODE DIBAWAH INI :
"""def input_matrix():
    baris = int(input("Masukkan jumlah baris: "))
    kolom = int(input("Masukkan jumlah kolom: "))
    matrix = []
    for i in range(baris):
        row = []
        print(f"Masukkan elemen untuk baris {i + 1}: ")
        for j in range(kolom):
            element = float(input(f"Elemen [{i + 1}, {j + 1}]: "))
            row.append(element)
        matrix.append(row)
    return matrix

print("Program perkalian matriks!!")
print("Masukkan matriks pertama:")
matriks1 = input_matrix()
print ("Matriks 1 = ", matriks1)
print("Masukkan matriks kedua:")
matriks2 = input_matrix()
print ("Matriks 2 = ",matriks2)
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)"""


print ("Berikut adalah contoh matriks")
print ("""
matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])
""")
matriks1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks2=([[2,4,7],[6,-3,2],[5,-2,7]])
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)


Berikut adalah contoh matriks

matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])


Hasil perkalian matriks:
[32, -5, 34]
[-1, 19, 9]
[-4, -2, 3]


In [7]:
import numpy as np
import sympy as sy

a=np.array([[3,2,1, 2],[5,4,2, 3],[2,5, 1, 4], [3, 5, 7, 2]])
b=np.array([[3,2,6, 4],[7,1,4, 5],[2,-2,6, 9]])

print('A=\n',a)
print()
print('B=\n',b)
print()
C = b.transpose()
print(C)
print()
D = a @ C
print(D)


A=
 [[3 2 1 2]
 [5 4 2 3]
 [2 5 1 4]
 [3 5 7 2]]

B=
 [[ 3  2  6  4]
 [ 7  1  4  5]
 [ 2 -2  6  9]]

[[ 3  7  2]
 [ 2  1 -2]
 [ 6  4  6]
 [ 4  5  9]]

[[27 37 26]
 [47 62 41]
 [38 43 36]
 [69 64 56]]


REFERENSI:   
- https://www.pijarbelajar.id/blog/operasi-matriks-penjumlahan-pengurangan-dan-perkalian-beserta-contoh-soalnya      
- https://www.gramedia.com/literasi/transpose-matriks/     
- https://numpy.org/doc/stable/reference/generated/numpy.matrix.transpose.html         