Matriks adalah kumpulan bilangan yang disusun dalam baris dan kolom. Secara formal, matriks dapat dijelaskan sebagai sebuah array persegi panjang yang terdiri dari elemen-elemen yang disusun dalam baris dan kolom. Setiap elemen dalam matriks dapat diidentifikasi oleh indeks baris dan kolomnya. Misalnya, sebuah matriks \( A \) dengan \( m \) baris dan \( n \) kolom dapat ditulis sebagai:

A = $$ \begin{bmatrix} a_{11} & a_{12} & \dots & a_{1n} \\ a_{21} & a_{22} & \dots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \dots & a_{mn} \end{bmatrix}  $$

Di mana \( a_{ij} \) merupakan elemen pada baris ke-\( i \) dan kolom ke-\( j \).

Matriks sering digunakan dalam berbagai bidang seperti matematika, fisika, teknik, dan ilmu komputer untuk merepresentasikan dan menyelesaikan berbagai masalah. Matriks digunakan dalam berbagai aplikasi seperti sistem persamaan linear, transformasi geometri, analisis jaringan, dan pemrograman linier.

Berikut adalah beberapa contoh perumpamaan yang dapat membantu Anda memahami konsep matriks secara lebih mendalam:

1. **Sistem Persamaan Linear**:
   Bayangkan Anda memiliki sebuah sistem persamaan linear, misalnya:
   $$
   \begin{align*}
   2x + 3y &= 8 \\
   4x - 2y &= 6
   \end{align*}
   $$
   Anda dapat merepresentasikan koefisien dari variabel \( x \) dan \( y \) dalam bentuk matriks:
   $$
   \begin{bmatrix}
   2 & 3 \\
   4 & -2
   \end{bmatrix}
   $$
   $$
   \begin{bmatrix}
   x \\
   y
   \end{bmatrix}
   =
   $$
   $$
   \begin{bmatrix}
   8 \\
   6
   \end{bmatrix}
   $$
   Di sini, matriks koefisien digunakan untuk mengalikan vektor variabel \( x \) dan \( y \) sehingga hasilnya sama dengan vektor hasil.

2. **Transformasi Geometri**:
   Ketika Anda melakukan transformasi geometri seperti rotasi, translasi, atau dilatasi pada suatu objek, Anda dapat menggunakan matriks transformasi untuk merepresentasikan perubahan yang terjadi. Misalnya, jika Anda ingin memutar sebuah vektor dua dimensi \( \begin{bmatrix} x \\ y \end{bmatrix} \) sebesar \( \theta \) derajat searah jarum jam, Anda dapat menggunakan matriks rotasi:
   $$
   
   \begin{bmatrix}
   \cos(\theta) & -\sin(\theta) \\
   \sin(\theta) & \cos(\theta)
   \end{bmatrix}
   \begin{bmatrix}
   x \\
   y
   \end{bmatrix}
   $$

3. **Analisis Jaringan**:
   Dalam analisis jaringan, matriks dapat digunakan untuk merepresentasikan hubungan antar simpul (node) dalam sebuah jaringan. Misalnya, dalam jaringan transportasi, setiap elemen matriks dapat mewakili biaya atau jarak antara dua simpul yang terhubung.

4. **Pemrograman Linier**:
   Dalam pemrograman linier, matriks digunakan untuk merepresentasikan koefisien dari fungsi tujuan dan kendala-kendala dalam bentuk matriks dan vektor. Ini membantu dalam pemecahan masalah optimasi yang melibatkan pemaksimalan atau peminimalan fungsi tujuan dengan mempertimbangkan sejumlah kendala.

Dengan memahami konsep matriks dan penerapannya dalam berbagai bidang, Anda dapat melihat betapa pentingnya matriks dalam merepresentasikan dan menyelesaikan berbagai masalah matematika dan komputasi.

#**JENIS JENIS MATRIKS**
1. **Matriks Nol**:
   Ini adalah matriks di mana semua elemennya adalah nol. Misalnya, matriks nol \( 3 \times 3 \) ditulis sebagai:
   $$
   \begin{bmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0
   \end{bmatrix}
   $$

2. **Matriks Baris**:
   Ini adalah matriks dengan satu baris dan beberapa kolom. Misalnya, sebuah matriks baris \( 1 \times 4 \) adalah:
   $$
   \begin{bmatrix}
   1 & 2 & 3 & 4
   \end{bmatrix}
   $$

3. **Matriks Kolom**:
   Ini adalah matriks dengan satu kolom dan beberapa baris. Contohnya, sebuah matriks kolom \( 3 \times 1 \) adalah:
   $$
   \begin{bmatrix}
   1 \\
   2 \\
   3
   \end{bmatrix}
   $$

4. **Matriks Persegi**:
   Matriks yang memiliki jumlah baris sama dengan jumlah kolomnya. Misalnya, matriks persegi \( 2 \times 2 \) adalah:
   $$
   \begin{bmatrix}
   1 & 2 \\
   3 & 4
   \end{bmatrix}
   $$

5. **Matriks Diagonal**:
   Matriks dengan elemen selain diagonal utamanya adalah nol. Contoh:
   $$
   \begin{bmatrix}
   1 & 0 & 0 \\
   0 & 4 & 0 \\
   0 & 0 & 7
   \end{bmatrix}
   $$

6. **Matriks Skalar**:
   Matriks diagonal dengan semua elemen diagonal utamanya sama. Misalnya, matriks skalar \( 3 \times 3 \) dengan skalar \( 2 \) adalah:
   $$
   \begin{bmatrix}
   2 & 0 & 0 \\
   0 & 2 & 0 \\
   0 & 0 & 2
   \end{bmatrix}
   $$

7. **Matriks Identitas**:
   Ini adalah matriks skalar dengan elemen diagonal utamanya semua sama dengan satu. Misalnya, matriks identitas \( 3 \times 3 \) adalah:
   $$
   \begin{bmatrix}
   1 & 0 & 0 \\
   0 & 1 & 0 \\
   0 & 0 & 1
   \end{bmatrix}
   $$

8. **Matriks Simetris**:
   Matriks persegi di mana setiap elemen selain elemen diagonalnya adalah simetris terhadap diagonal utama. Misalnya:
   $$
   \begin{bmatrix}
   1 & 2 & 3 \\
   2 & 4 & 5 \\
   3 & 5 & 6
   \end{bmatrix}
   $$

9. **Matriks Simetri Miring**:
   Matriks di mana elemen di bawah diagonal utamanya adalah negatif dari elemen di atas diagonal utamanya. Contoh:
   $$
   \begin{bmatrix}
   0 & 1 & 2 \\
   -1 & 0 & 3 \\
   -2 & -3 & 0
   \end{bmatrix}
   $$
   

10. **Matriks Segitiga Atas**:
    Matriks persegi di mana elemen-elemen di bawah diagonal utamanya adalah nol. Misalnya:
    $$
    \begin{bmatrix}
    1 & 2 & 3 \\
    0 & 4 & 5 \\
    0 & 0 & 6
    \end{bmatrix}
    $$

11. **Matriks Segitiga Bawah**:
    Matriks persegi di mana elemen-elemen di atas diagonal utamanya adalah nol. Contoh:
    $$
    \begin{bmatrix}
    1 & 0 & 0 \\
    4 & 5 & 0 \\
    7 & 8 & 9
    \end{bmatrix}
    $$

12. **Matriks Transpose**:
    Matriks yang diperoleh dengan menukar baris dan kolom. Misalnya, jika \( A \) adalah matriks \( m x n \), maka transpose \( A \) adalah matriks \( n x m \) dengan elemen-elemen \( a_{ij} \) menjadi \( a_{ji} \).

Semua jenis matriks ini memiliki aplikasi dan sifat matematis yang berbeda-beda dan penting dalam berbagai bidang ilmu.

### **OPERASI MATRIKS**
Operasi matriks adalah serangkaian operasi atau tindakan yang dilakukan pada matriks, baik itu untuk mengubah matriks ataupun menggabungkan matriks. Berikut beberapa operasi matriks yang sering digunakan:

In [1]:
import numpy as np
import sympy as sy

a=np.array([[4,2,1],[5,3,1],[2,-3,4]])
b=np.array([[3,2,6],[7,1,4],[2,-2,6]])
c=np.array([[5,2],[-4,7],[6,5]])
print('A=\n',a)
print('B=\n',b)
print('C=\n',c)

A=
 [[ 4  2  1]
 [ 5  3  1]
 [ 2 -3  4]]
B=
 [[ 3  2  6]
 [ 7  1  4]
 [ 2 -2  6]]
C=
 [[ 5  2]
 [-4  7]
 [ 6  5]]


### **1.Penjumlahan matriks :**

Operasi ini melibatkan penambahan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENJUMLAHAN MATRIKS A + B :
matriks \( A \):
$$
A = \begin{bmatrix}
4 & 2 & 1 \\
5 & 3 & 1 \\
2 & -3 & 4
\end{bmatrix}
$$


Matriks \( B \):
$$
B = \begin{bmatrix}
3 & 2 & 6 \\
7 & 1 & 4 \\
2 & -2 & 6
\end{bmatrix}
$$

Hasil Penjumlahan Matriks \( A \) dan \( B \):
$$
A + B = \begin{bmatrix}
4+3 & 2+2 & 1+6 \\
5+7 & 3+1 & 1+4 \\
2+2 & -3-2 & 4+6
\end{bmatrix}  
$$
Jadi, hasil penjumlahan dari matriks \( A \) dan \( B \) adalah:
$$
A + B = \begin{bmatrix}
7 & 4 & 7 \\
12 & 4 & 5 \\
4 & -5 & 10
\end{bmatrix}
$$

BERIKUT PROGRAM UNTUK PENJUMLAHAN MATRIKS:



In [2]:
print('A+B=\n',a+b)
print('B+A=\n',b+a)
print('Sifat di atas merupakan sifat komutatif karena A+B = B+A')

A+B=
 [[ 7  4  7]
 [12  4  5]
 [ 4 -5 10]]
B+A=
 [[ 7  4  7]
 [12  4  5]
 [ 4 -5 10]]
Sifat di atas merupakan sifat komutatif karena A+B = B+A


##**2.Pengurangan Matriks:**

Operasi ini melibatkan pengurangan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENGURANGAN MATRIKS:   
Matriks \( A \):
$$
A = \begin{bmatrix}
4 & 2 & 1 \\
5 & 3 & 1 \\
2 & -3 & 4
\end{bmatrix}
$$

Matriks \( B \):
$$
B = \begin{bmatrix}
3 & 2 & 6 \\
7 & 1 & 4 \\
2 & -2 & 6
\end{bmatrix}
$$

Hasil Pengurangan Matriks \( A \) dan \( B \):
$$
A - B = \begin{bmatrix}
4-3 & 2-2 & 1-6 \\
5-7 & 3-1 & 1-4 \\
2-2 & -3-(-2) & 4-6
\end{bmatrix}
$$
Jadi, hasil pengurangan dari matriks \( A \) dan \( B \) adalah:
$$
A - B = \begin{bmatrix}
1 & 0 & -5 \\
-2 & 2 & -3 \\
0 & -1 & -2
\end{bmatrix}
$$
BERIKUT PROGRAM UNTUK PENGURANGAN MATRIKS:

In [3]:
print('A-B=\n',a-b)
print('B-A=\n',b-a)
print('Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A')

A-B=
 [[ 1  0 -5]
 [-2  2 -3]
 [ 0 -1 -2]]
B-A=
 [[-1  0  5]
 [ 2 -2  3]
 [ 0  1  2]]
Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A


##**3.Perkalian Matriks:**

Operasi ini melibatkan perkalian elemen-elemen matriks. Untuk melakukan perkalian matriks A dan B, jumlah kolom dalam matriks A harus sama dengan jumlah baris dalam matriks B. Contoh matriks A memiliki ordo atau ukuran mxn, maka matriks B harus memiliki ordo atau ukuran nxp. Sehingga hasil dari perkalian tersebut akan menghasilkan matriks baru dengan ukuran mxp. Hasilnya akan memiliki jumlah baris yang sama dengan matriks A dan jumlah kolom yang sama dengan matriks B.

CONTOH PERKALIAN MATRIKS:


Dengan menggunakan matriks \(A\) dan \(B\) yang Anda berikan, mari kita hitung hasil perkalian \(A \times B\):

 A = 
 $$\begin{bmatrix} 4 & 2 & 1 \\ 5 & 3 & 1 \\ 2 & -3 & 4 \end{bmatrix} $$

 B = 
 $$\begin{bmatrix} 3 & 2 & 6 \\ 7 & 1 & 4 \\ 2 & -2 & 6 \end{bmatrix}$$

Untuk menghitung hasil perkalian matriks, kita dapat menggunakan aturan perkalian matriks, yaitu mengalikan setiap elemen baris pertama dari matriks \(A\) dengan setiap elemen kolom pertama dari matriks \(B\), dan seterusnya.


A × B = 
$$\begin{bmatrix} 4 \times 3 + 2 \times 7 + 1 \times 2 & 4 \times 2 + 2 \times 1 + 1 \times (-2) & 4 \times 6 + 2 \times 4 + 1 \times 6 \\ 5 \times 3 + 3 \times 7 + 1 \times 2 & 5 \times 2 + 3 \times 1 + 1 \times (-2) & 5 \times 6 + 3 \times 4 + 1 \times 6 \\ 2 \times 3 + (-3) \times 7 + 4 \times 2 & 2 \times 2 + (-3) \times 1 + 4 \times (-2) & 2 \times 6 + (-3) \times 4 + 4 \times 6 \end{bmatrix}$$




Jadi, hasil perkalian matriks \(A\) dan \(B\) adalah:

 A x B = 
 $$\begin{bmatrix} 24 & 2 & 32 \\ 38 & 3 & 44 \\ -13 & -12 & 10 \end{bmatrix}$$

BERIKUT PROGRAM UNTUK PERKALIAN MATRIKS:

In [4]:
print('AB=\n',a@b)
print('AC=\n',a@c)
print('BC=\n',b@c)

AB=
 [[28  8 38]
 [38 11 48]
 [-7 -7 24]]
AC=
 [[18 27]
 [19 36]
 [46  3]]
BC=
 [[43 50]
 [55 41]
 [54 20]]


- Sifat Asosiasi:

  (AB)C = A(BC)

In [5]:
print('A(BC) =\n', a@(b@c))
print('(AB)C =\n',(a@b)@c)

A(BC) =
 [[336 302]
 [434 393]
 [137  57]]
(AB)C =
 [[336 302]
 [434 393]
 [137  57]]


- Perkalian skalar:

  c(AB) = (cA)B = A(cB)

In [6]:
c = 3
print('c(AB)\n',c*(a@b))
print('(cA)B\n',(c*a)@b)
print('A(cB)\n',a@(c*b))

c(AB)
 [[ 84  24 114]
 [114  33 144]
 [-21 -21  72]]
(cA)B
 [[ 84  24 114]
 [114  33 144]
 [-21 -21  72]]
A(cB)
 [[ 84  24 114]
 [114  33 144]
 [-21 -21  72]]


- Perkalian identitas:

  AI = IA = A

In [7]:
i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 4  2  1]
 [ 5  3  1]
 [ 2 -3  4]]
IA=
 [[ 4  2  1]
 [ 5  3  1]
 [ 2 -3  4]]
A=
 [[ 4  2  1]
 [ 5  3  1]
 [ 2 -3  4]]


- Tidak berlaku sifat kumutatif:

  AB != BA atau AB tidak sama dengan BA

In [8]:
print('AB=\n',a@b)
print('BA=\n',b@a)

AB=
 [[28  8 38]
 [38 11 48]
 [-7 -7 24]]
BA=
 [[ 34  -6  29]
 [ 41   5  24]
 [ 10 -20  24]]


##**4.Transpose Matriks**

Transpose matriks adalah matriks baru yang diperoleh dengan cara menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya. Jika sebuah matriks berukuran M X N, maka transpose matriks tersebut memiliki ordo N X M.

CONTOH TRANSPOSE MATRIKS:
$$
\begin{align*}
C=
\begin{bmatrix}
3&4\\
-2&4\\
2&5
\end{bmatrix}
&&
CT (C Transposre)=
\begin{bmatrix}
3&-2&2\\
4&4&-5
\end{bmatrix}
\end{align*}
$$
BERIKUT PROGRAM UNTUK MENG-TRANSPOSE MATRIKS:

In [9]:
c=np.array([[3,4],[-2,4],[2,5]])
c_tran = c.transpose()
print('matrik c sebelum di transpose=\n', c)
print('matrik c setelah di transpose=\n',c_tran)
print('ordo C_transpose adalah',c_tran.shape)
z=c_tran@c
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=c@c_tran
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)
print("Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose")

matrik c sebelum di transpose=
 [[ 3  4]
 [-2  4]
 [ 2  5]]
matrik c setelah di transpose=
 [[ 3 -2  2]
 [ 4  4  5]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[17 14]
 [14 57]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[25 10 26]
 [10 20 16]
 [26 16 29]]
ordo P adalah (3, 3)
Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose


program untuk mengalikan matrix

In [10]:
def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)

#JIKA USER INGIN MENGINPUTKAN MATRIKSNYA SENDIRI BISA MENGGUNAKAN CODE DIBAWAH INI :
"""def input_matrix():
    baris = int(input("Masukkan jumlah baris: "))
    kolom = int(input("Masukkan jumlah kolom: "))
    matrix = []
    for i in range(baris):
        row = []
        print(f"Masukkan elemen untuk baris {i + 1}: ")
        for j in range(kolom):
            element = float(input(f"Elemen [{i + 1}, {j + 1}]: "))
            row.append(element)
        matrix.append(row)
    return matrix

print("Program perkalian matriks!!")
print("Masukkan matriks pertama:")
matriks1 = input_matrix()
print ("Matriks 1 = ", matriks1)
print("Masukkan matriks kedua:")
matriks2 = input_matrix()
print ("Matriks 2 = ",matriks2)
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)"""


print ("Berikut adalah contoh matriks")
print ("""
matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])
""")
matriks1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks2=([[2,4,7],[6,-3,2],[5,-2,7]])
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)


Berikut adalah contoh matriks

matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])


Hasil perkalian matriks:
[32, -5, 34]
[-1, 19, 9]
[-4, -2, 3]
