## **MATRIX INVERS**
Invers Matriks: Kebalikan yang Menghasilkan Identitas

Bayangkan sebuah matriks seperti papan susunan angka, bisa persegi panjang atau persegi. invers matriks adalah seperti kunci ajaib yang bisa "membalik" matriks tersebut. Kunci ini, dinotasikan dengan A-1, yang jika dikalikan dengan matriks asal (A), hasilnya akan selalu menjadi matriks identitas.

sifat sifat:       

- Hanya untuk matriks persegi **non-singular** (det ≠ 0).                         
- Unik untuk setiap matriks.               
- $(Z^{-1})^{-1} = Z$                                    
- $(YZ)^{-1} = (Z^{-1})Y^{-1}$                              
- $(Z^{T})^{-1} = (Z^{-1})^{T}$                                     
- $(I^{-1}) = I$                              
I adalah matriks identitas.                    
Z adalah matriks persegi. 



## Mencari Matriks Invers dengan Eliminasi Gauss-Jordan 

**Langkah-langkah:**

**1. Bentuk Matriks Identitas:**

- Buatlah matriks identitas (I) dengan ukuran 2x2.

$$
I = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
$$

**2. Gabungkan Matriks:**

- Gabungkan matriks A dengan matriks identitas I secara horizontal.

$$
A_g = \begin{bmatrix}
A & | & I \\
\end{bmatrix} = \begin{bmatrix}
4 & 4 & | & 1 & 0 \\
3 & 2 & | & 0 & 1
\end{bmatrix}
$$

**3. Lakukan Operasi Per Baris:**

- **Langkah a:** Kalikan baris 1 dengan 1/4 agar elemen pada baris 1 kolom 1 menjadi 1.

$$
A_g = \begin{bmatrix}
1 & 1 & | & 1/4 & 0 \\
3 & 2 & | & 0 & 1
\end{bmatrix}
$$

- **Langkah b:** Kurangi baris 2 dengan (R2 = R2-3R1).

$$
A_g = \begin{bmatrix}
1 & 1 & | & 1/4 & 0 \\
0 & -1 & | & -3/4 & 1
\end{bmatrix}
$$

- **Langkah c:** Kalikan baris 2 dengan -1.

$$
A_g = \begin{bmatrix}
1 & 1 & | & 1/4 & 0 \\
0 & 1 & | & 3/4 & -1
\end{bmatrix}
$$

- **Langkah d:** Kurangi baris 1 dengan baris 2.

$$
A_g = \begin{bmatrix}
1 & 0 & | & -1/4 & 1 \\
0 & 1 & | & 3/4 & -1
\end{bmatrix}
$$

**4. Matriks Invers:**

- Matriks di sebelah kiri (setelah operasi baris) merupakan invers dari matriks A.

$$
A^{-1} = \begin{bmatrix}
-1/4 & 1 \\
3/4 & -1
\end{bmatrix}
$$



 **MENYELESAIKAN SISTEM PERSAMAAN LINEAR 4 VARIABLE DENGAN METODE GAUSS JORDAN**    

persamaan:               
 $ 2x1 + x2 + 0x3 + 2x4 = 5 $                      
 $ 1x1 + 0x2 + 2x3 + 1x4 = 6$                      
 $ 1x1 + 2x2 + 1x3 + 0x4 = 7$                 
 $ 1x1 + 1x2 + 0x3 + 2x4 = 8 $                            


ubah kedalam bentuk matrix 
$$
A = \begin{bmatrix}
2 & 1 & 0 &2 & | & 5\\
1 & 0 & 2 & 1 & | & 6\\
1 & 2 & 1 & 0 & | & 7\\
1 & 1 & 0 & 2 & | & 8
\end{bmatrix}
$$

Menulis matriks augemented:

$$
\begin{bmatrix}
2 & 1 & 0 &2 & | & 1 & 0 & 0 & 0\\                
1 & 0 & 2 & 1& | & 0 & 1 & 0 & 0\\           
1 & 2 & 1 & 0 &| &  0 & 0 & 1 & 0\\              
1 & 1 & 0 & 2 & | & 0 & 0 & 0 & 1   
\end{bmatrix}
$$

penyelesaian:                                                     
pertama deklarasikan RowSwap, RowAdd, RowScale


In [1]:

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
#buat numpy array matriks Augemented
import numpy as np
A = np.array([[2,1,0,2, 1,0,0,0], [1,0,2,1, 0,1,0,0], [1,2,1,0,0,0,1,0], [1,1,0,2, 0,0,0,1]])
print(A)

[[2 1 0 2 1 0 0 0]
 [1 0 2 1 0 1 0 0]
 [1 2 1 0 0 0 1 0]
 [1 1 0 2 0 0 0 1]]


In [3]:
#tambahkan -1 kali baris 1 ke baris 0
B1 = RowAdd(A, 1, 0, -1)
print(B1)
print()

# tambahkan -1 kali baris 0 ke baris 1
B2 = RowAdd(B1, 0, 1, -1)
print(B2)
print()

# tambahkan -1 kali baris 0 ke baris 2
B3 = RowAdd(B2, 0, 2, -1)
print(B3)
print()

# tambahkan -1 kali baris 0 ke baris 3
B4 = RowAdd(B3, 0, 3, -1)
print(B4)

[[ 1.  1. -2.  1.  1. -1.  0.  0.]
 [ 1.  0.  2.  1.  0.  1.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.  1.  0.]
 [ 1.  1.  0.  2.  0.  0.  0.  1.]]

[[ 1.  1. -2.  1.  1. -1.  0.  0.]
 [ 0. -1.  4.  0. -1.  2.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.  1.  0.]
 [ 1.  1.  0.  2.  0.  0.  0.  1.]]

[[ 1.  1. -2.  1.  1. -1.  0.  0.]
 [ 0. -1.  4.  0. -1.  2.  0.  0.]
 [ 0.  1.  3. -1. -1.  1.  1.  0.]
 [ 1.  1.  0.  2.  0.  0.  0.  1.]]

[[ 1.  1. -2.  1.  1. -1.  0.  0.]
 [ 0. -1.  4.  0. -1.  2.  0.  0.]
 [ 0.  1.  3. -1. -1.  1.  1.  0.]
 [ 0.  0.  2.  1. -1.  1.  0.  1.]]


In [4]:
# tambahkan 1 kali baris 1 ke baris 0
C1 = RowAdd(B4, 1, 0, 1)
print(C1)
print()

#tambahkan 2 kali baris dua ke baris 1
C2 = RowAdd(C1, 2, 1, 2 )
print(C2)
print()

#tambahkan -1 kali baris 1 ke baris 2
C3 = RowAdd(C2, 1, 2, -1)
print(C3)

[[ 1.  0.  2.  1.  0.  1.  0.  0.]
 [ 0. -1.  4.  0. -1.  2.  0.  0.]
 [ 0.  1.  3. -1. -1.  1.  1.  0.]
 [ 0.  0.  2.  1. -1.  1.  0.  1.]]

[[ 1.  0.  2.  1.  0.  1.  0.  0.]
 [ 0.  1. 10. -2. -3.  4.  2.  0.]
 [ 0.  1.  3. -1. -1.  1.  1.  0.]
 [ 0.  0.  2.  1. -1.  1.  0.  1.]]

[[ 1.  0.  2.  1.  0.  1.  0.  0.]
 [ 0.  1. 10. -2. -3.  4.  2.  0.]
 [ 0.  0. -7.  1.  2. -3. -1.  0.]
 [ 0.  0.  2.  1. -1.  1.  0.  1.]]


In [5]:
#tambahkan -1 kali baris 3 ke baris 0
D1 = RowAdd(C3, 3, 0, -1 )
print(D1)
print()

# kalikan 1/2 ke baris 3
D2 = RowScale (D1, 3, 1/2)
print(D2)
print()

# pindahkan baris 3 ke baris 2
D3 = RowSwap (D2, 3, 2)
print(D3)
print()

# tambahkan -10 kali baris 2 ke baris 1
D4 = RowAdd(D3, 2, 1, -10)
print(D4)
print()

# tambahkan 7 kali baris 2 ke baris 3
D5 = RowAdd(D4, 2, 3, 7)
print(D5)

[[ 1.  0.  0.  0.  1.  0.  0. -1.]
 [ 0.  1. 10. -2. -3.  4.  2.  0.]
 [ 0.  0. -7.  1.  2. -3. -1.  0.]
 [ 0.  0.  2.  1. -1.  1.  0.  1.]]

[[ 1.   0.   0.   0.   1.   0.   0.  -1. ]
 [ 0.   1.  10.  -2.  -3.   4.   2.   0. ]
 [ 0.   0.  -7.   1.   2.  -3.  -1.   0. ]
 [ 0.   0.   1.   0.5 -0.5  0.5  0.   0.5]]

[[ 1.   0.   0.   0.   1.   0.   0.  -1. ]
 [ 0.   1.  10.  -2.  -3.   4.   2.   0. ]
 [ 0.   0.   1.   0.5 -0.5  0.5  0.   0.5]
 [ 0.   0.  -7.   1.   2.  -3.  -1.   0. ]]

[[ 1.   0.   0.   0.   1.   0.   0.  -1. ]
 [ 0.   1.   0.  -7.   2.  -1.   2.  -5. ]
 [ 0.   0.   1.   0.5 -0.5  0.5  0.   0.5]
 [ 0.   0.  -7.   1.   2.  -3.  -1.   0. ]]

[[ 1.   0.   0.   0.   1.   0.   0.  -1. ]
 [ 0.   1.   0.  -7.   2.  -1.   2.  -5. ]
 [ 0.   0.   1.   0.5 -0.5  0.5  0.   0.5]
 [ 0.   0.   0.   4.5 -1.5  0.5 -1.   3.5]]


In [6]:
# kalikan 2/9 ke baris 3
E1 = RowScale(D5, 3, 2/9)
print(E1)
print()

#tambahkan 7 kali baris 3 ke baris 1
E2 = RowAdd(E1, 3, 1, 7)
print(E2)
print()

#tambahkan -0.5 kali baris 3 ke baris 2
E3 = RowAdd(E2, 3, 2, -0.5)
print(E3)

[[ 1.          0.          0.          0.          1.          0.
   0.         -1.        ]
 [ 0.          1.          0.         -7.          2.         -1.
   2.         -5.        ]
 [ 0.          0.          1.          0.5        -0.5         0.5
   0.          0.5       ]
 [ 0.          0.          0.          1.         -0.33333333  0.11111111
  -0.22222222  0.77777778]]

[[ 1.          0.          0.          0.          1.          0.
   0.         -1.        ]
 [ 0.          1.          0.          0.         -0.33333333 -0.22222222
   0.44444444  0.44444444]
 [ 0.          0.          1.          0.5        -0.5         0.5
   0.          0.5       ]
 [ 0.          0.          0.          1.         -0.33333333  0.11111111
  -0.22222222  0.77777778]]

[[ 1.          0.          0.          0.          1.          0.
   0.         -1.        ]
 [ 0.          1.          0.          0.         -0.33333333 -0.22222222
   0.44444444  0.44444444]
 [ 0.          0.          1.   

Pembuktian :

A (X) = B

maka,

X = 
$$
\begin{align*}(A^-1)B\end{align*}
$$

In [7]:
AI = np.array([[1, 0, 0, -1],[-0.33333333,-0.22222222,0.44444444, 0.44444444],[-0.33333333, 0.44444444, 0.1111111, 0.11111111],[-0.33333333, 0.11111111, -0.22222222,0.77777778 ]])
b = np.array([[5], [6], [7], [8]])
print("Ax = b")
print(f"Ax = {b}")

print("\n")
print("x = A^-1 b")
AI1 = AI @ b
print(f"x = {AI1}")

Ax = b
Ax = [[5]
 [6]
 [7]
 [8]]


x = A^-1 b
x = [[-3.        ]
 [ 3.66666663]
 [ 2.66666657]
 [ 3.66666671]]


ditemukan:             
$ x1 = -3 $      
$ x2 = 3.66666663 $           
$ x3 = 2.66666657 $    
$ x4 = 3.66666671 $    

subtitusi :          
 $ 2(-3) + 1(3.66666663) + 0(2.66666657) + 2(3.66666671) = 5.00000005 ----- dibulatkan (5)$             
 $ 1(-3) + 0(3.66666663) + 2(2.66666657) + 1(3.66666671)= 5.99999985 ----- dibulatkan (6) $             
 $ 1(-3)+ 2(3.66666663) + 1(2.66666657)+ 0(3.66666671) = 6.99999983 ---- dibulatkan (7) $                
 $ 1(-3)+ 1(3.66666663) + 0(2.66666657) + 2(3.66666671) = 8.00000083 ---- dibulatkan (8) $                 

 Pembuktian :



In [8]:
C = AI @ A
print(C.round())

[[ 1.  0.  0.  0.  1.  0.  0. -1.]
 [ 0.  1.  0.  0. -0. -0.  0.  0.]
 [-0. -0.  1.  0. -0.  0.  0.  0.]
 [ 0.  0.  0.  1. -0.  0. -0.  1.]]


referensi:
- https://www.gramedia.com/literasi/pengertian-invers-matriks/
- https://www.youtube.com/watch?v=nkEEbwrG4k4